# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFontDatabase
import os

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        path=os.path.dirname(os.path.abspath(__file__))
        QFontDatabase.addApplicationFont(path+"\\fonts\\Inter-Medium.ttf")
        QFontDatabase.addApplicationFont(path+"\\fonts\\Inter-Regular.ttf")
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(400, 565)
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setStyleSheet("QDialog {\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(Dialog)
        self.title_label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(17)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.client_lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        self.client_lineEdit.setFont(font)
        self.client_lineEdit.setMouseTracking(True)
        self.client_lineEdit.setStyleSheet("border: 1px solid rgb(197, 197, 197);\n"
"border-radius: 5px;\n"
"padding: 4px;")
        self.client_lineEdit.setObjectName("client_lineEdit")
        self.verticalLayout.addWidget(self.client_lineEdit)
        self.device_lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        self.device_lineEdit.setFont(font)
        self.device_lineEdit.setStyleSheet("border: 1px solid rgb(197, 197, 197);\n"
"border-radius: 5px;\n"
"padding: 4px;")
        self.device_lineEdit.setObjectName("device_lineEdit")
        self.verticalLayout.addWidget(self.device_lineEdit)
        self.service_lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        self.service_lineEdit.setFont(font)
        self.service_lineEdit.setStyleSheet("border: 1px solid rgb(197, 197, 197);\n"
"border-radius: 5px;\n"
"padding: 4px;")
        self.service_lineEdit.setObjectName("service_lineEdit")
        self.verticalLayout.addWidget(self.service_lineEdit)
        self.status_comboBox = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        self.status_comboBox.setFont(font)
        self.status_comboBox.setStyleSheet("QComboBox {\n"
"font-size: 13pt;\n"
"padding: 4px;\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(197, 197, 197);\n"
"}\n"
"QComboBox::drop-down {\n"
"border: 0px;\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/icon/icons/down-arrow.png);\n"
"width: 15px;\n"
"height: 15px;\n"
"margin-right: 15px;\n"
"}\n"
"QComboBox QListView {\n"
"border: 0px;\n"
"outline: 0px;\n"
"}")
        self.status_comboBox.setEditable(False)
        self.status_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.status_comboBox.setFrame(True)
        self.status_comboBox.setObjectName("status_comboBox")
        self.status_comboBox.addItem("")
        self.status_comboBox.addItem("")
        self.verticalLayout.addWidget(self.status_comboBox)
        self.price_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.price_lineEdit.setValidator(QtGui.QIntValidator())
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        self.price_lineEdit.setFont(font)
        self.price_lineEdit.setStyleSheet("border: 1px solid rgb(197, 197, 197);\n"
"border-radius: 5px;\n"
"padding: 4px;")
        self.price_lineEdit.setObjectName("price_lineEdit")
        self.verticalLayout.addWidget(self.price_lineEdit)
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("padding: 4px;\n"
"border: 1px solid rgb(197, 197, 197);\n"
"border-radius: 5px;")
        self.dateEdit.setWrapping(False)
        self.dateEdit.setFrame(True)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit.setAccelerated(False)
        self.dateEdit.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        self.phone_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.phone_lineEdit.setValidator(QtGui.QIntValidator())
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        self.phone_lineEdit.setFont(font)
        self.phone_lineEdit.setStyleSheet("border: 1px solid rgb(197, 197, 197);\n"
"border-radius: 5px;\n"
"padding: 4px;")
        self.phone_lineEdit.setObjectName("phone_lineEdit")
        self.verticalLayout.addWidget(self.phone_lineEdit)
        self.master_comboBox = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        self.master_comboBox.setFont(font)
        self.master_comboBox.setStyleSheet("QComboBox {\n"
"font-size: 13pt;\n"
"padding: 4px;\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(197, 197, 197);\n"
"}\n"
"QComboBox::drop-down {\n"
"border: 0px;\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/icon/icons/down-arrow.png);\n"
"width: 15px;\n"
"height: 15px;\n"
"margin-right: 15px;\n"
"}\n"
"QComboBox QListView {\n"
"border: 0px;\n"
"outline: 0px;\n"
"}")
        self.master_comboBox.setEditable(False)
        self.master_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.master_comboBox.setFrame(True)
        self.master_comboBox.setObjectName("master_comboBox")
        self.master_comboBox.addItem("")
        self.master_comboBox.addItem("")
        self.verticalLayout.addWidget(self.master_comboBox)
        self.comment_lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        self.comment_lineEdit.setFont(font)
        self.comment_lineEdit.setStyleSheet("border: 1px solid rgb(197, 197, 197);\n"
"border-radius: 5px;\n"
"padding: 4px;")
        self.comment_lineEdit.setObjectName("comment_lineEdit")
        self.verticalLayout.addWidget(self.comment_lineEdit)
        self.add_Button = QtWidgets.QPushButton(Dialog)
        self.add_Button.setMinimumSize(QtCore.QSize(0, 50))
        self.add_Button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add_Button.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(16)
        self.add_Button.setFont(font)
        self.add_Button.setStyleSheet("border: 0px;\n"
"background-color: rgb(84, 252, 120);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 16pt;\n"
"border-radius: 6px;")
        self.add_Button.setObjectName("add_Button")
        self.verticalLayout.addWidget(self.add_Button)

        self.retranslateUi(Dialog)
        self.status_comboBox.setCurrentIndex(0)
        self.master_comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_label.setText(_translate("Dialog", "Новый заказ"))
        self.client_lineEdit.setPlaceholderText(_translate("Dialog", "Клиент"))
        self.device_lineEdit.setPlaceholderText(_translate("Dialog", "Устройство"))
        self.service_lineEdit.setPlaceholderText(_translate("Dialog", "Услуга"))
        self.status_comboBox.setItemText(0, _translate("Dialog", "Активен"))
        self.status_comboBox.setItemText(1, _translate("Dialog", "Выполнен"))
        self.price_lineEdit.setPlaceholderText(_translate("Dialog", "Стоимость"))
        self.phone_lineEdit.setPlaceholderText(_translate("Dialog", "Номер телефона"))
        self.master_comboBox.setItemText(0, _translate("Dialog", "Константин"))
        self.master_comboBox.setItemText(1, _translate("Dialog", "Михаил"))
        self.comment_lineEdit.setPlaceholderText(_translate("Dialog", "Комментарий"))
        self.add_Button.setText(_translate("Dialog", "Добавить"))
import icons_dialog
